# Generated by Django 4.1.7 on 2023-05-08 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_reporttt'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reporttt',
        ),
    ]
