# Generated by Django 4.0.5 on 2023-03-17 04:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rep'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rep',
            name='name',
        ),
    ]
