# Generated by Django 4.1.7 on 2023-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_uploadimage_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadimage',
            name='caption',
            field=models.CharField(default='Untitled', max_length=255),
        ),
    ]
