# Generated by Django 4.0.5 on 2023-03-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_hours_department_remove_hours_entry_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='registration',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact_number', models.CharField(max_length=50)),
                ('date_of_birth', models.CharField(max_length=50)),
                ('date_of_joining', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('designation', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=50)),
                ('team', models.CharField(max_length=50)),
            ],
        ),
    ]
