# Generated by Django 4.1.7 on 2023-05-16 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_uploadimage_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
