# Generated by Django 5.1.3 on 2024-12-07 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_uploadimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='detected_in',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
