# Generated by Django 4.0.5 on 2023-03-23 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_registration'),
    ]

    operations = [
        migrations.DeleteModel(
            name='registration',
        ),
        migrations.AddField(
            model_name='employee',
            name='password',
            field=models.CharField(default='', max_length=50),
        ),
    ]
