# Generated by Django 5.1.3 on 2024-12-09 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_detected_in_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='detected_out',
            name='name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
    ]
