# Generated by Django 4.0.5 on 2023-03-24 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_name_employee_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='user',
            new_name='name',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
