# Generated by Django 5.1.3 on 2024-12-18 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_detected_out_photo_alter_rep_emp_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('employee', 'date')},
        ),
    ]
