# Generated by Django 4.0.5 on 2023-03-25 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_login'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Login',
        ),
    ]
